### ISSUE TITLE
Can't compile rbdoom3-bfg: CMake Error at CMakeLists.txt:388 (include)

### ISSUE THREAD

**Issue by Samson7** [GoGoOtaku/GoGoOverlay#2]
I got this error during configure:
```
CMake Error at CMakeLists.txt:388 (include):
include could not find requested file: /usr/lib64/cmake/glslangTargets.cmake
CMake Error at CMakeLists.txt:389 (include):
include could not find requested file: /usr/lib64/cmake/SPIRVTargets.cmake
CMake Error at CMakeLists.txt:409 (add_subdirectory):
The source directory /var/tmp/portage/games-fps/rbdoom3-bfg-1.4.0/work/RBDOOM-3-BFG-1.4.0/neo/extern/glslang does not contain a CMakeLists.txt file.
```
full build log: 
[bfg.log](https://github.com/GoGoOtaku/GoGoOverlay/files/15369224/bfg.log)

**Comment by GoGoOtaku** [comment]
This is fixed now.

Keep in mind tho that this is an oldish version of RBDoom3-BFG.
Version 1.5.0 was a huge rewrite which broke Linux and AMD support somewhat and only with 1.5.1 has this been mostly fixed.
With some additional back-ports I've managed to get it to compile but now some assert fails on startup.
An assert that perceivable should not be able to fail on my setup.

Anyway: If I manage to get it to compile and run properly on my system I will update to 1.5.1 but until then it's a bit outdated. This is just a heads-up that it's oldish.
